### PR TITLE
use NSSet for common platform use case

### PR DESCRIPTION
**Pull request by flovilmart**
Just because I saw that on twitter, you may reject it, I don't really mind, but instead of bad mouthing I prefer contributing :)

### CODE REVIEW

**Comment by Kapeli** [comment]
Thank you! ❤️

**Comment by danielpunkass** [comment]
Just want to say I don't think the original code even merits 1/100th the criticism it has received. The code is correct, and that counts for a ton. It's easy to imagine how this particular code could have grown crazier over time but never been the focus of @Kapeli's priorities, because he was busy, you know, making the app great.

In my opinion anybody who savors criticism of this code should do some soul-searching to decide whether every line of code in your own projects meets your own standard. Alternatively: if you have such high standards that you can justify the criticism, just how successful are you at shipping successful products that customers love?

**Comment by flovilmart** [comment]
I can't agree more with you @danielpunkass ...

**Comment by Kapeli** [comment]
My 2 cents: I think it's okay to discuss and criticise and maybe even make fun of bad code, so we can learn and avoid it in the future. Some will cross the line and be insulting, as this is the Internet after all, but we shouldn't avoid discussing things just because some of us can't be civilised.

I don't think @BalestraPatrick did anything wrong with his tweet and a lot of the discussion surrounding it was about optimising that code, which is great.

Dash contains a lot of silly code and hacks. So anyone reading this: go ahead and find it and discuss it and criticise it. I won't mind.

**Comment by danielpunkass** [comment]
It's great to hear that @Kapeli has a thick skin and won't be bothered by open criticism.

I encourage anybody who takes his offer to remember that publicly criticising somebody, laughing at their work, diminishing their achievements, has an effect on the onlookers of the criticism, even if the person you are criticizing insists they can take it.

Hate to draw parallels between things like this and the current state of world politics, but in my opinion we all need to practice being more kind. There is a well-established mechanism for kind criticism on GitHub, in the form of tickets and pull requests. Enjoying a public mockery of somebody, away from the context of the work tiself, e.g. on Twitter, does not strike me as a great demonstration of kindness.

**Comment by Kapeli** [comment]
@danielpunkass To clarify: I am encouraging people to discuss/criticise parts of my code that aren't so great, while keeping it civilised. I'm not encouraging anyone to make fun of my work as a whole or of my programming skills, just individual pieces of code.

Bad code needs to be discussed. We can do that kindly and without insulting someone. Trolls will always be around on the Internet, we should not suppress our discussions because of them.

**Comment by Kapeli** [comment]
Also: discussing on Twitter vs GitHub has the advantage of reaching more people which can learn from it. This does have the drawback of trolls insulting, but we should shame the trolls and not the person that started the conversation.

**Pull request merged**
