### PR TITLE
bugFix: two gray line appear when device rotate from horizontal regular to horizontal compact

### PR DESCRIPTION
**Pull request by zhongwuzw**
bug reproduce:
1. let device in horizontal regular state;
2. search some key(ps. has search results);
3. rotate device to horizontal compact state; then appear two gray line.

### CODE REVIEW

**Comment by zhongwuzw** [comment]
## screenshot:
-----

635c804e241ae9497eff8f047d2fdf04

* I think it's a iOS system bug.

**Comment by Kapeli** [comment]
I still get a gray line with your fix:

simulator screen shot 16 nov 2016 12 35 42

I've seen these bugs in all iOS apps I've tried when rotating between portait/landscape or landscape/portrait, including Apple apps. The gray lines aren't the only issue, the whole search results table view seems to reposition.

Maybe we should fix it by ending the search and redoing it on rotation?

**Comment by zhongwuzw** [comment]
@Kapeli I updated the code, this time, I don`t remove top gray line, just adjust tableView insets.

**Comment by Kapeli** [comment]
This fixes the tableview part of the bug, but the searchbar doesn't reposition properly, so you still get something like this when switching from landscape to portrait:

6397d3e4-abf9-11e6-915d-b1c650f59529

Deactivating & reactivating the search controller seems to fix all bugs, but it's ugly as it loses scroll position and redoes the search: https://github.com/Kapeli/Dash-iOS/commit/ee49a6ec98cc107febfd074372c69e87c04892e3. I don't really like it.

I'll try to expand on your fix and get the searchbar to reposition properly.

**Comment by zhongwuzw** [comment]
@Kapeli , yeah, I agree with you, deactivating & reactivating seems not user friendly. If wants to position searchBar under statusBar, I think we can add code `self.edgesForExtendedLayout = UIRectEdgeNone;` to viewController.

**Comment by Kapeli** [comment]
`self.edgesForExtendedLayout = UIRectEdgeNone` changes the way the status bar is drawn. Doesn't look good in my opinion.

simulator screen shot 17 nov 2016 20 38 06

Found these radars regarding this issue: https://openradar.appspot.com/21743785 and https://openradar.appspot.com/352525

**Comment by zhongwuzw** [comment]
@Kapeli , I changes the statusBar color by set `DHSplitViewController` backgroundColor. because of set `self.edgesForExtendedLayout = UIRectEdgeNone`, we should revise `DHNavigationAnimator`. 

I also fix the docset download interface bug(reproduce step: in download interface,click searchBar,rotate,input some search key). screenshot below:

**Comment by Kapeli** [comment]
I think this is going to extreme lengths to partially fix a bug that's on Apple's end. I'd much rather leave things as is and have the bug present like every other app on iOS. I'm afraid we'll introduce a bunch of other bugs trying to fix this one.

**Comment by zhongwuzw** [comment]
Yep, I'll close the pull request.

**Pull request closed without merging**
